"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$git_branch\
$package\
$directory\
$python\
$character\
"""

palette = "rose-pine"

[palettes.rose-pine]
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'
text = '#e0def4'

[character]
disabled = false
format = "$symbol "
success_symbol = "[|](fg:text)"
error_symbol = "[|](fg:love)"

[directory]
disabled = false
format = " [$path]($style) "
style = "fg:foam"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
disabled = false
format = " [$symbol$branch]($style), "
style = "fg:rose"
symbol = " "

[package]
disabled = false
format = " [$symbol$version]($style), "
style = "fg:gold"
symbol = " "

[python]
format = '[(\($virtualenv\) )]($style)'
style = "fg:pine"
