"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$python\
$git_branch\
$directory\
"""

palette = "rose-pine"

[palettes.rose-pine]
base = '#191724'
surface = '#1f1d2e'
overlay = '#26233a'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'
text = '#e0def4'
subtle = '#908caa'
muted = '#6e6a86'
highlight-low = '#21202e'
highlight-med = '#403d52'
highlight-high = '#524f67'

[directory]
disabled = false
format = "[ $path ]($style) "
style = "bg:overlay fg:text"
# truncation_length = 3
# truncation_symbol = "…/"

[git_branch]
disabled = false
format = "[ $symbol$branch ]($style)"
style = "bg:surface fg:text"
symbol = " "

[python]
format = '[(\($virtualenv\) )]($style)'
style = "fg:iris"
